// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoaD7VDCnXJ3TVXTQGaDqDjtXSuPG7s28',
    appId: '1:378705323250:web:856c3e5c9a966a71ce9c6b',
    messagingSenderId: '378705323250',
    projectId: 'ahtdimigo',
    authDomain: 'ahtdimigo.firebaseapp.com',
    databaseURL: 'https://ahtdimigo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahtdimigo.appspot.com',
    measurementId: 'G-NH5CJE71TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5P4C1q4K52SFHjdFz6CTSUliixM3jiSs',
    appId: '1:378705323250:android:8a24fafb8ae7eb01ce9c6b',
    messagingSenderId: '378705323250',
    projectId: 'ahtdimigo',
    databaseURL: 'https://ahtdimigo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahtdimigo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcTOgjfAFWtK-68UtRwG90Phcw-ct2GA',
    appId: '1:378705323250:ios:f0ecbd5273100cdfce9c6b',
    messagingSenderId: '378705323250',
    projectId: 'ahtdimigo',
    databaseURL: 'https://ahtdimigo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahtdimigo.appspot.com',
    iosClientId: '378705323250-gktl59kgo590a0nmbig49ruql3nk6imp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahtDimigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIcTOgjfAFWtK-68UtRwG90Phcw-ct2GA',
    appId: '1:378705323250:ios:367501dd9315e33ace9c6b',
    messagingSenderId: '378705323250',
    projectId: 'ahtdimigo',
    databaseURL: 'https://ahtdimigo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahtdimigo.appspot.com',
    iosClientId: '378705323250-cjt11l1oedike1t4ts3uhgn79adfhbc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahtDimigo.RunnerTests',
  );
}
