// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35e_XE9bv_pLJXsc_M71vrTYsy0ncBEE',
    appId: '1:490830252827:web:e04031f47dd1815e6ee1be',
    messagingSenderId: '490830252827',
    projectId: 'aht-a9dbe',
    authDomain: 'aht-a9dbe.firebaseapp.com',
    storageBucket: 'aht-a9dbe.appspot.com',
    measurementId: 'G-VZ00R2B71V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkeGmc5gEZyTP8NKv3i2c0YvHGWyUIsMk',
    appId: '1:490830252827:android:685322672429058a6ee1be',
    messagingSenderId: '490830252827',
    projectId: 'aht-a9dbe',
    storageBucket: 'aht-a9dbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybV-P8S6Quq3knxvCx-2FVD-FoT9VgtA',
    appId: '1:490830252827:ios:9a4b9d1f055e4d006ee1be',
    messagingSenderId: '490830252827',
    projectId: 'aht-a9dbe',
    storageBucket: 'aht-a9dbe.appspot.com',
    iosClientId: '490830252827-37g10qt3jav2crf06d2pqp4gquvgk9s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahtDimigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAybV-P8S6Quq3knxvCx-2FVD-FoT9VgtA',
    appId: '1:490830252827:ios:8f675b577f0cdab36ee1be',
    messagingSenderId: '490830252827',
    projectId: 'aht-a9dbe',
    storageBucket: 'aht-a9dbe.appspot.com',
    iosClientId: '490830252827-fbvdpq61j11ian7uq6psovmftokpsoto.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahtDimigo.RunnerTests',
  );
}
